package storage

const (
KNOWN_SUPERNODE_EDGE ="KNOWN_NODE"
KNOWN_PEER_EDGE ="KNOWN_APP"
KNOWN_APPKEY_EDGE ="KNOWN_APPKEY"
EXPORT_EDGE       = "EXPORT"
	IMPORT_EDGE       = "IMPORT"
TAG_EDGE          = "HAS_TAG"
implements_edge   = "IMPLEMENTS"
AWAITING_JOB_EDGE = "AWAITING_JOB"
DOING_JOB_EDGE    = "DOING_JOB"
LISTEN_EDGE       = "LISTEN"

	result_edge = "HAS_RESULT"
)

